name: textize documents

inputs:
  root: { required: false, type: string }

runs:
  using: composite
  steps:

    - uses: office-tecoli/actions-use-perl-tools@main
      with:
        tools: App::optex::textconv

    - id: make-txt
      shell: bash
      run: |
        root=${{ inputs.root }}
        : ${root:=.}
        for file in $(find $root -name '*.docx' -print)
        do
            txt=${file%.*}.txt
            if [ -f $txt ]
            then
                echo $txt exists
            else
                optex -Mtextconv cat $file > ${file%.*}.txt
            fi
        done
