name: textize documents

inputs:
  root:   { required: false, type: string }
  branch: { required: false, type: string, default: textize }
  token:  { required: true, default: '${{ github.token }}' }

runs:
  using: composite
  steps:

    - uses: office-tecoli/actions-use-any-tools@v0
      with:
        perl: App::optex::textconv
        apt:  poppler-utils

    - id: textize
      shell: bash
      run: |
        : textize
        root=${{ inputs.root }}
        : ${root:=.}
        textize=$GITHUB_ACTION_PATH/textize.sh
        files=$(git ls-files $root)
        echo Processing $files ...
        update=$( $textize $files )
        echo $update
        cat << END
        ::set-output name=update::$update
        END

    - id: export
      shell: bash
      run: |
        : export
        set -x; printenv
        update="${{ steps.textize.outputs.update }}"
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        TOKEN="${{ inputs.token }}"
        BRANCH="${{ inputs.branch }}"
        remote_repo="https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        echo $remote_repo
        git checkout -B $BRANCH
        git add $update
        git commit -m "update $update"
        git push $remote_repo
