name: textize documents

inputs:
  root:   { required: false, type: string }
  branch: { required: false, type: string, default: textize }

runs:
  using: composite
  steps:

    - uses: office-tecoli/actions-use-any-tools@v0
      with:
        perl: App::optex::textconv
        apt:  poppler-utils

    - id: textize
      shell: bash
      run: |
        root=${{ inputs.root }}
        : ${root:=.}
        textize=$GITHUB_ACTION_PATH/textize.sh
        update=$( $textize $(git ls-files $root) )
        cat << END
        ::set-output update=$update
        END

    - id: export
      shell: bash
      run: |
        echo ${{ steps.outputs.update }}
        git branch
        git status
