name: textize documents

inputs:
  root:   { required: false, type: string }
  branch: { required: false, type: string, default: textize }

runs:
  using: composite
  steps:

    - uses: office-tecoli/actions-use-any-tools@v0
      with:
        perl: App::optex::textconv
        apt:  poppler-utils

    - id: make-txt
      shell: bash
      run: |
        root=${{ inputs.root }}
        : ${root:=.}
        for file in $(
            find $root \
                \( \
                    -name '*.docx' -o -name '*.docm' -o -name '*.doc' -o \
                    -name '*.pptx' -o -name '*.pptm' -o \
                    -name '*.pdf' \
                \) \
                -print \
        )
        do
            txt=${file/%.*/.txt}
            if [ -f $txt ]
            then
                echo $txt exists
            else
                optex -Mtextconv cat $file > $txt
                cat -n $txt
            fi
        done

    - id: export
      shell: bash
      run: |
        git branch
        git status

