name: test

on:
  push:
    branches-ignore:
      - textize
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          root: __test__
      - run: |
          : check result
          ls -lR
          for txt in $(find . -name '*.txt' -print)
          do
            echo $txt:
            cat -n $txt | head -20
          done
